### ISSUE TITLE
تصحیح وتغییر سناریو

### ISSUE THREAD

**Issue by FATEMEPOURSADEGHI** [FATEMEPOURSADEGHI/Library_project#2]
#2
- [x] موجودیت های پروژه رابه فایل سناریو اضافه کنید.
- [x] از لیست در فایل های سناریو استفاده کنید

**Comment by Mohadesehrajabzadeh** [comment]
انجام شد لطفا چک کنید

**Comment by FATEMEPOURSADEGHI** [comment]
بسیار خوب.
